[package]
name = "chunk_sum"
version = "0.1.0"
authors = ["Frank Andrew Stevenson <frankstevensonmobile@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
